include:
  - project: devops/gitlab-ci-common
    ref: master
    file: /public/_variables.yml
  - project: devops/gitlab-ci-common
    ref: master
    file: /public/_commitlint.yml
  - project: devops/gitlab-ci-common
    ref: master
    file: /public/_bump.yml
  - project: devops/gitlab-ci-common
    ref: master
    file: /public/test/go.yml

.test_template:
  variables:
    PROJECT_PATH: /go/src/github.com/tomwganem/${CI_PROJECT_NAME}
