[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.3.0"

[[constraint]]
  name = "gopkg.in/square/go-jose.v2"
  version = "2.2.2"

[[constraint]]
  name = "github.com/getsentry/raven-go"
  version = "0.2.0"

[prune]
  go-tests = true
  unused-packages = true
