---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  jwtsecret: c2VjcmV0
---
apiVersion: v1
kind: Service
metadata:
  name: example-jwt-auth
spec:
  type: ClusterIP
  selector:
    app: example-jwt-auth
  ports:
  - port: 3000
    name: http-example-auth
    targetPort: 3000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example-jwt-auth
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: example-jwt-auth
    spec:
      containers:
      - name: example-jwt-auth
        image: kminehart/ambassador-auth-jwt:v1.0.0
        imagePullPolicy: Always
        ports:
        - name: http-api
          containerPort: 3000
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: jwtsecret
        - name: JWT_COOKIE_NAME
          value: session_token
        - name: CHECK_EXP
          value: "true"
        resources:
          limits:
            cpu: "0.1"
            memory: 100Mi

